### ISSUE TITLE
not working on VRChat Build 1201

### ISSUE THREAD

**Issue by BloodWorkVR** [ddakebono/BTKSASelfPortrait#5] opened 2022-05-26 10:47 UTC
clicking the button does nothing anymore

**Comment by RealityWarper** [comment] 2022-05-26 12:01
Quick and dirty fix for code to build and work on version 1201 is to update "/UserInterface/UnscaledUI/HudContent" to "/UserInterface/UnscaledUI/HudContent_Old".

**Comment by BloodWorkVR** [comment] 2022-05-26 12:18
i do not know how to do any of this but alright

**Comment by RealityWarper** [comment] 2022-05-26 12:21
The issue is simple to fix, sit tight, author will likely update the release Soon™.

**Comment by ddakebono** [comment] 2022-05-26 13:48
I haven't had time to review all my mods yet, I'll look at fixing this issue tonight, as it is an easy one. The update will depend on it getting past the review process for VRCMG.

**Comment by ddakebono** [comment] 2022-05-27 00:29
Fixed as of release 1.2.2, publish to VRCMG in progress.

**Closed as completed by ddakebono** 2022-05-27 00:29 UTC
